# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_C13ksVHBaHiQjtKa6mdV4HP0wUjchnW
"""

import numpy as np
from numpy import random
for i in range (5):
  arr= random.randint(100,size=(10))
  print(np.sort(arr))